analysis/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
	openapi.Info(
		title = "My Machine Learning API",
		default_version = 'v1',
		description = "ML Problem Statement:Predicting Term Deposit Suscriptions.\n Author:Ranjith Kumar Sangi",
		),
		public = True,
		permission_classes = (permissions.AllowAny,),
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/',include('prediction.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('',include('project.urls')),
	url(r'^swagger(?P<format>\.json|\.yaml)$',schema_view.without_ui(cache_timeout=None),name='schema-json'),
	url(r'^swagger/$',schema_view.with_ui('swagger',cache_timeout=None),name='schema-swagger-ui'),
    url(r'^redoc/$',schema_view.with_ui('redoc',cache_timeout=None),name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'dashboard'

urlpatterns = [
	path('train/', views.TrainMobile.as_view(), name = 'train'),
	path('train/<str:mobile>', views.TrainReviewView.as_view(), name = 'train_mobile')
]

project/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'project'

urlpatterns = [
	path('', views.IndexView.as_view(), name = 'index'),
	path('sentiment-analysis/', views.AnalysisMobileReview.as_view(), name = 'mobile_list'),
	path('sentiment-analysis/<str:mobile>/', views.AnalysisMobileReview.as_view(), name = 'analysis'),
	path('getMobileData/', views.GetMobileData.as_view(), name = 'getMobileData'),
	path('getMobileCameraData/', views.GetMobileCameraData.as_view(), name = 'getMobileCameraData'),
	path('getMobileBatteryData/', views.GetMobileBatteryData.as_view(), name = 'getMobileBatteryData'),
	path('getMobileMemoryData/', views.GetMobileMemoryData.as_view(), name = 'getMobileMemoryData'),
]

project/models.py
from django.db import models

# Create your models here.

project/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.views import View

import json

from dashboard.models import Mobile, MobileReviews
from dashboard.utils import total_trained_data
from .fonAPI import FonApi

fon = FonApi('31483eeecdbe6a708eeae0cd3c3edb76920e3442e7a611fb')

class IndexView(View):

    def get(self, request):
        context = {}
        mobiles_count = Mobile.objects.count
        mobiles = Mobile.objects.all
        reviews_count = MobileReviews.objects.count
        train_count = total_trained_data()
        context = {
            'mobiles_count':mobiles_count,
            'mobiles':mobiles,
            'reviews_count':reviews_count,
            'train_count':train_count,
        }
        return render(request, 'project/index.html', context)


class AnalysisMobileReview(View):

    def get(self, request, mobile=None):
        context = {}

        if mobile:
            mobile = get_object_or_404(Mobile, slug=mobile)
            context['mobile'] = mobile
            device = mobile.name
            phone = fon.getdevice(device)[0]
            context['phone'] = phone
            print(phone)

            return render(request, 'project/analysis.html', context)

        mobiles = Mobile.objects.all
        context['mobiles'] = mobiles
        return render(request, 'project/mobiles.html', context)

    def post(self, request):
        context = {}
        return redirect('project:analysis', request.POST['mobile'])

class GetMobileData(View):

    def post(self, request):
        mobile = get_object_or_404(Mobile, slug=request.POST['slug'])
        reviews = get_list_or_404(MobileReviews.objects.values_list('rating', flat=True), mobile=mobile)

        high = reviews.count(5)
        average = reviews.count(2)+reviews.count(3)+reviews.count(4)
        low = reviews.count(1)
        total = high + average + low

        dict = {}
        dict['low'] = {'y' : int((low/total)*100), 'name' : 'Low'}
        dict['average'] = {'y' : int((average/total)*100), 'name' : 'Average'}
        dict['high'] = {'y' : int((high/total)*100), 'name' : 'High'}

        return HttpResponse(json.dumps(dict), content_type="application/json")

class GetMobileCameraData(View):

    def post(self, request):
        mobile = get_object_or_404(Mobile, slug=request.POST['slug'])
        reviews = get_list_or_404(MobileReviews.objects.filter(review__contains='camera' \
          ).values_list('rating', flat=True), mobile=mobile)

        high = reviews.count(5)
        average = reviews.count(2)+reviews.count(3)+reviews.count(4)
        low = reviews.count(1)
        total = high + average + low

        dict = {}
        dict['low'] = {'y' : int((low/total)*100), 'name' : 'Low'}
        dict['average'] = {'y' : int((average/total)*100), 'name' : 'Average'}
        dict['high'] = {'y' : int((high/total)*100), 'name' : 'High'}

        return HttpResponse(json.dumps(dict), content_type="application/json")

class GetMobileBatteryData(View):

    def post(self, request):
        mobile = get_object_or_404(Mobile, slug=request.POST['slug'])
        reviews = get_list_or_404(MobileReviews.objects.filter(review__contains='battery' \
          ).values_list('rating', flat=True), mobile=mobile)

        high = reviews.count(5)
        average = reviews.count(2)+reviews.count(3)+reviews.count(4)
        low = reviews.count(1)
        total = high + average + low

        dict = {}
        dict['low'] = {'y' : int((low/total)*100), 'name' : 'Low'}
        dict['average'] = {'y' : int((average/total)*100), 'name' : 'Average'}
        dict['high'] = {'y' : int((high/total)*100), 'name' : 'High'}

        return HttpResponse(json.dumps(dict), content_type="application/json")

class GetMobileMemoryData(View):

    def post(self, request):
        mobile = get_object_or_404(Mobile, slug=request.POST['slug'])
        reviews = get_list_or_404(MobileReviews.objects.filter(review__contains='ram' \
          ).values_list('rating', flat=True), mobile=mobile)

        high = reviews.count(5)
        average = reviews.count(2)+reviews.count(3)+reviews.count(4)
        low = reviews.count(1)
        total = high + average + low

        dict = {}
        dict['low'] = {'y' : int((low/total)*100), 'name' : 'Low'}
        dict['average'] = {'y' : int((average/total)*100), 'name' : 'Average'}
        dict['high'] = {'y' : int((high/total)*100), 'name' : 'High'}

        return HttpResponse(json.dumps(dict), content_type="application/json")

project/templates/project/analysis.html
{% extends "project/base.html" %}
{% load static %}

{% block javascript %}
	<script type="text/javascript">
		var slug = "{{mobile.slug}}"
	</script>
	<script src="{% static 'project/js/graph.js' %} "></script>
{% endblock  %}

{% block content %}

<div class="breadcomb-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="breadcomb-list">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<div class="breadcomb-wp">
								<div class="breadcomb-icon">
									<i class="notika-icon notika-bar-chart"></i>
								</div>
								<div class="breadcomb-ctn">
									<h2>{{mobile.name}}</h2>
									<p><span class="bread-ntd">Mobile Analysis</span></p>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="sale-statistic-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
                <div class="sale-statistic-inner notika-shadow mg-tb-30">
                    <div class="curved-inner-pro">
                        <div class="curved-ctn">
                            <h2>Overall Analysis</h2>
                            <p>Based on all reviews for this phone.</p>
                        </div>
                    </div>
                    <div id="chartContainer" style="height: 300px; width: 100%;"></div>
										<form class="" action="" method="post">
											{% csrf_token %}
										</form>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
                <div class="statistic-right-area notika-shadow mg-tb-30 sm-res-mg-t-0">
									<div class="recent-post-ctn">
											<div class="recent-post-title">
													<h2>{{mobile.name}}</h2>
											</div>
									</div>
									<div class="recent-post-items">
											<div class="recent-post-signle rct-pt-mg-wp">
													<div class="recent-post-flex">
															<div class="recent-post-it-ctn">
																	<h2>Brand</h2>
																	<span>{{phone.Brand}}</span>
															</div>
													</div>
											</div>
											<br>
											<div class="recent-post-signle rct-pt-mg-wp">
													<div class="recent-post-flex">
															<div class="recent-post-it-ctn">
																	<h2>Size</h2>
																	<span>{{phone.size}}</span>
															</div>
													</div>
											</div>
											<br>
											<div class="recent-post-signle rct-pt-mg-wp">
													<div class="recent-post-flex">
															<div class="recent-post-it-ctn">
																	<h2>Features</h2>
																	<span>{{phone.features_c}}</span>
															</div>
													</div>
											</div>

									</div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="visitor-sv-tm-area">
		<div class="container">
				<div class="row">
						<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
								<div class="visitor-sv-tm-int">
										<div class="contact-hd mg-bt-ant-inner">
												<h2>Camera</h2>
										</div>
										<div class="visitor-sv-tm-ch">
												<div id="cameraAnalysis" style="height: 150px; width: 100%;"></div>
												<p style="margin-top:30px">{{phone.primary_}} and {{phone.secondary}}</p>
										</div>
								</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
								<div class="visitor-sv-tm-int sm-res-mg-t-30">
										<div class="contact-hd mg-bt-ant-inner server-sts-rgt">
												<h2>Battery</h2>
										</div>
										<div class="visitor-st-ch">
												<div id="batteryAnalysis" style="height: 150px; width: 100%;"></div>
												<p style="margin-top:30px">{{phone.battery_c}}</p>
										</div>
								</div>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
								<div class="visitor-sv-tm-int sm-res-mg-t-30 tb-res-mg-t-30 tb-res-ds-n dk-res-ds">
										<div class="contact-hd mg-bt-ant-inner">
												<h2>Memory</h2>
										</div>
										<div class="visitor-st-ch visitor-ov-ct">
												<div id="memoryAnalysis" style="height: 150px; width: 100%;"></div>
												<p style="margin-top:30px">{{phone.internal}}({{phone.os}})</p>
										</div>
								</div>
						</div>
				</div>
		</div>
</div>


{% endblock  %}

project/templates/project/analysis0.html
<!DOCTYPE HTML>
<html>
<head>
<script>
window.onload = function () {
  var token = $('input[name=csrfmiddlewaretoken]').val();

  $.ajax({
    type: "POST",
    url: "/project/getMobileData/",
    data: {
        csrfmiddlewaretoken: token,
        slug: "{{mobile.slug}}"
    },
    success: function(data) {
					console.log(data);
          list = []
					for(key in data){
            var i = 0;
            var temp = {};
            if(key=='high'){
              temp['exploded'] = true
            }
            for(val in data[key]){
              if(i==0){
                temp['y'] = data[key][val];
                i = 1;
              }else{
                temp['name'] = data[key][val];
              }
            }
            list.push(temp)
					}
          console.log(list);

          var chart = new CanvasJS.Chart("chartContainer", {
          	exportEnabled: true,
          	animationEnabled: true,
          	title:{
          		text: "{{mobile.name}} - Analyize"
          	},
          	legend:{
          		cursor: "pointer",
          		itemclick: explodePie
          	},
          	data: [{
          		type: "pie",
          		showInLegend: true,
          		toolTipContent: "{name}: <strong>{y}%</strong>",
          		indexLabel: "{name} - {y}%",
          		dataPoints: list
          	}]
          });
          chart.render();

    },
    error: function(ts) {
          alert(ts.responseText)
    }
  });


}

function explodePie (e) {
	if(typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
		e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
	} else {
		e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
	}
	e.chart.render();

}
</script>
</head>
<body>
  <form class="" action="" method="post">
    {% csrf_token %}
  </form>
  <div id="chartContainer" style="height: 300px; width: 100%;"></div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html>

project/templates/project/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Project</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'project/img/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'project/css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/owl.carousel.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/owl.theme.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/owl.transitions.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/meanmenu/meanmenu.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/animate.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/normalize.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/scrollbar/jquery.mCustomScrollbar.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/notika-custom-icon.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/wave/waves.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/wave/button.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/main.css' %} ">
    <link rel="stylesheet" href="{% static 'project/style.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/responsive.css' %} ">
    <script src="{% static 'project/js/vendor/modernizr-2.8.3.min.js' %} "></script>
    {% block javascript %}
    {% endblock  %}
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <a href="{% url 'project:index' %}"><img src="{% static 'project/img/logo.png' %}" alt="Project Name" /></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="header-top-menu">
                        <ul class="nav navbar-nav notika-top-nav">
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span><i class="notika-icon notika-search"></i></span></a>
                                <div role="menu" class="dropdown-menu search-dd animated flipInX">
                                    <div class="search-input">
                                        <i class="notika-icon notika-left-arrow"></i>
                                        <input type="text" />
                                    </div>
                                </div>
                            </li>


                            <li class="nav-item">
                              <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                              <span><i class="notika-icon notika-menus"></i></span>
                              </a>
                                <div role="menu" class="dropdown-menu message-dd task-dd animated zoomIn">
                                    <div class="hd-mg-tt">
                                        <h2>Tasks</h2>
                                    </div>
                                    <div class="hd-message-info hd-task-info">
                                        <div class="skill">
                                            <div class="progress">
                                                <div class="lead-content">
                                                    <p>HTML5 Validation Report</p>
                                                </div>
                                                <div class="progress-bar wow fadeInLeft" data-progress="95%" style="width: 95%;" data-wow-duration="1.5s" data-wow-delay="1.2s"> <span>95%</span>
                                                </div>
                                            </div>
                                            <div class="progress">
                                                <div class="lead-content">
                                                    <p>Google Chrome Extension</p>
                                                </div>
                                                <div class="progress-bar wow fadeInLeft" data-progress="85%" style="width: 85%;" data-wow-duration="1.5s" data-wow-delay="1.2s"><span>85%</span> </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li><a data-toggle="collapse" data-target="#Charts" href="#">Home</a>
                                    <ul class="collapse dropdown-header-top">
                                        <li><a href="index.html">Home</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li class="active">
                          <a href="{% url 'project:index' %}"><i class="notika-icon notika-house"></i> Home</a>
                        </li>
                        <li>
                          <a href="{% url 'admin:index' %}"><i class="notika-icon notika-support"></i> Admin</a>
                        </li>
                        <li>
                          <a href="{% url 'dashboard:train' %}"><i class="notika-icon notika-app"></i> Train</a>
                        </li>

                    </ul>

                </div>
            </div>
        </div>
    </div>
    <!-- Main Menu area End-->
    <!-- Start Status area -->
      {% block status %}
      {% endblock  %}

    <!-- End Status area-->
    <!-- Start Sale Statistic area-->
    {% block content %}
    {% endblock  %}
    <!-- End Sale Statistic area-->


    <!-- Start Footer area-->
    <div class="footer-copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="footer-copy-right">
                        <p>Project © 2018
. All rights reserved. <!-- Template by <a href="https://colorlib.com">Colorlib</a>.--></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer area-->
    <!-- jquery
		============================================ -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="{% static 'project/js/vendor/jquery-1.12.4.min.js' %} "></script>
    <script src="{% static 'project/js/bootstrap.min.js' %} "></script>
    <script src="{% static 'project/js/wow.min.js' %} "></script>
    <script src="{% static 'project/js/jquery-price-slider.js' %} "></script>
    <script src="{% static 'project/js/owl.carousel.min.js' %} "></script>
    <script src="{% static 'project/js/jquery.scrollUp.min.js' %} "></script>
    <script src="{% static 'project/js/meanmenu/jquery.meanmenu.js' %} "></script>
    <script src="{% static 'project/js/counterup/jquery.counterup.min.js' %} "></script>
    <script src="{% static 'project/js/counterup/waypoints.min.js' %} "></script>
    <script src="{% static 'project/js/counterup/counterup-active.js' %} "></script>
    <script src="{% static 'project/js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %} "></script>

    <script src="{% static 'project/js/sparkline/jquery.sparkline.min.js' %} "></script>
    <script src="{% static 'project/js/sparkline/sparkline-active.js' %} "></script>

    <script src="{% static 'project/js/plugins.js' %} "></script>
    <script src="{% static 'project/js/main.js' %} "></script>

</body>

</html>

project/templates/project/complete.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Project</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'project/css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/wave/waves.min.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/notika-custom-icon.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/main.css' %} ">
    <link rel="stylesheet" href="{% static 'project/style.css' %} ">
    <link rel="stylesheet" href="{% static 'project/css/responsive.css' %} ">
</head>

<body>
    <div class="error-page-area">
        <div class="error-page-wrap">
            <i class="notika-icon notika-alarm"></i>
            <h2>{{mobile.name}} <span class="counter">100</span>%</h2>
            <p>Mobile trained on latest trained model.</p>
            <a href="{% url 'project:index' %}" class="btn">Home</a>
        </div>
    </div>


    <script src="{% static 'project/js/vendor/jquery-1.12.4.min.js' %} "></script>
    <script src="{% static 'project/js/bootstrap.min.js' %} "></script>
    <script src="{% static 'project/js/counterup/jquery.counterup.min.js' %} "></script>
    <script src="{% static 'project/js/counterup/waypoints.min.js' %} "></script>
    <script src="{% static 'project/js/counterup/counterup-active.js' %} "></script>

</body>

</html>

project/templates/project/frontstats.html
<div class="notika-status-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                    <div class="website-traffic-ctn">
                        <h2><span class="counter">{{mobiles_count}}</span></h2>
                        <p>Total Mobiles</p>
                    </div>
                    <div class="sparkline-bar-stats1">9,4,8,6,5,6,4,8,3,5,9,5</div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
              <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
                <div class="website-traffic-ctn">
                  <h2><span class="counter">{{reviews_count}}</span></h2>
                  <p>Total Reviews</p>
                </div>
                <div class="sparkline-bar-stats3">4,2,8,2,5,6,3,8,3,5,9,5</div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30">
                    <div class="website-traffic-ctn">
                        <h2><span class="counter">{{train_count}}</span></h2>
                        <p>Train Model On Records</p>
                    </div>
                    <div class="sparkline-bar-stats2">1,4,8,3,5,6,4,8,3,3,9,5</div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wb-traffic-inner notika-shadow sm-res-mg-t-30 tb-res-mg-t-30 dk-res-mg-t-30">
                    <div class="website-traffic-ctn">
                        <h2><span class="counter">72.45</span>%</h2>
                        <p>Accuracy</p>
                    </div>
                    <div class="sparkline-bar-stats4">2,4,8,4,5,7,4,7,3,5,7,5</div>
                </div>
            </div>
        </div>
    </div>
</div>

project/templates/project/mobiles.html
<form class="" action="{% url 'project:mobile_list' %}" method="post">
{% csrf_token %}
<select class="" name="mobile" required>
  <option value="">Select Mobile</option>
  {% for data in mobiles %}
    <option value="{{data.slug}}">{{data.name}}</option>
  {% endfor %}
  <input type="submit" name="" value="Analysis">
</select>
</form>

project/templates/project/train.html
{% extends "project/base.html" %}
{% load static %}

{% block content %}

<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-phone"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Train Mobiles</h2>
										<p>Welcome to Notika <span class="bread-ntd">Train Mobile on Latest Trained Model</span></p>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

<div class="sale-statistic-area">
    <div class="container">
        <div class="row">

          {% for mobile in mobiles  %}
          <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
              <div class="statistic-right-area notika-shadow mg-tb-30 sm-res-mg-t-0">
                  <div class="past-day-statis">
                      <h2>{{mobile.name}}</h2>
                      <img src="{% static 'project/img/mobile.png' %}" alt="img of 127*207">
                  </div>
                  <div class="dash-widget-visits"></div>
                  <div class="past-statistic-an">
                      <div class="past-statistic-ctn">
                          <h3><span class="">{{mobile.company}}</span></h3>
                          <p>Smartphone</p>
                      </div>

                  </div>
                  <div class="past-statistic-an">
                    <a class="center" href="{% url 'dashboard:train_mobile' mobile.slug %}">
                      <button class="btn notika-btn-indigo btn-reco-mg btn-button-mg waves-effect btn-train ">Train Mobile</button>
                    </a>
                  </div>

              </div>
          </div>
          {% endfor %}

        </div>
    </div>
</div>
{% endblock  %}